config/routes.rb
Rails.application.routes.draw do
  root to: "tops#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  } 
  resources :programminglogs do
    resources :comments, only: :create
    resources :likes, only: [:index, :create, :destroy]
      collection do
        get 'search'
      end
    end
  resources :users, except: [:new]
  resources :expositions, only: [:index]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :programminglog, counter_cache: :likes_count
  validates_uniqueness_of :programminglog_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_programminglog, only: [:create, :destroy]

  def index
    @all_ranks = Programminglog.find(Like.group(:programminglog_id).order('count(programminglog_id) desc').limit(100).pluck(:programminglog_id))
  end

  def create
    @like = Like.create(user_id: current_user.id, programminglog_id: params[:programminglog_id])
    @likes = Like.where(programminglog_id: params[:programminglog_id])
    @programminglog.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, programminglog_id: params[:programminglog_id])
    like.destroy
    @likes = Like.where(programminglog_id: params[:programminglog_id])
    @programminglog.reload
  end

  private

  def set_programminglog
    @programminglog = Programminglog.find(params[:programminglog_id])
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% unless programminglog.like_user(current_user.id).blank? %>
    <%= link_to programminglog_like_path(programminglog_id: programminglog.id ,id: programminglog.likes[0].id), method: :delete, remote: true do %>
      <div class="vertical_like">
        いいね！<i class="fas fa-heart"></i>
        <span class="red-text">
          <%= programminglog.likes_count %>
        </span>
      </div>
    <% end %>
  <% else %>
    <%= link_to programminglog_likes_path(programminglog.id), method: :post, remote: true do %>
      <div class="vertical_like">
        いいね！<i class="far fa-heart"></i>
        <span class="grey-text text-darken-2">
          <%= programminglog.likes_count %>
        </span>
      </div>
    <% end %>
  <% end %>

<% else %>

  <% if programminglog.likes_count > 0 %>
    <div class="vertical_like">
      いいね！<i class="fas fa-heart"></i>
      <span class="red-text">
        <%= programminglog.likes_count %>
      </span>
    </div>
  <% else %>
    <div class="vertical_like">
      いいね！<i class="far fa-heart"></i>
      <span class="grey-text text-darken-2">
        <%= programminglog.likes_count %>
      </span>
    </div>
  <% end %>

<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @programminglog.id %>').html("<%= j(render partial: 'likes/like', locals: { programminglog: @programminglog}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @programminglog.id %>').html("<%= j(render partial: 'likes/like', locals: { programminglog: @programminglog}) %>");

app/views/likes/index.html.erb
<div class="likes_text">
  <div class="back-icon">
    <%= link_to programminglogs_path do %>
    <i class="fas fa-arrow-left"></i>
    <% end %>
  </div> 
  <div class="likes_rank">
    <i class="fas fa-heart"></i> good ranking
  </div>
  <div class="texts">
    <div class="text">
      <% @all_ranks.each.with_index(1) do |prolog, i|%>
        <div class="textonly">
          <%= link_to(programminglog_path(prolog.id), class: 'list-content') do %>
          <span class="ranking" id="rank<%= i %>">第<%= i %>位</span>
            <div class="text__left">
              <div class="text__image" style="background-image: url(<%= prolog.image %>);"></div>
            </div>
            <div class="text__right">
              <div class="text__title">
                <%= link_to prolog.title, programminglog_path(prolog.id), class: "content__right__top--title" %>
              </div>
              <div class="text__bottom">
                <div class="text__time">
                  <%= prolog.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
                </div>
                <div class="user__name">
                  <img src=<%= prolog.user.image %> class = "icon_image">
                  <div class="content__right__bottom--username">
                    <%= link_to prolog.user.name, user_path(prolog.user), class: "content__right__bottom--userName--btn" %>
                  </div>
                </div>
                <% prolog.tag_list.each do |tag| %>
                  <span style="background-color: #EEEEEE; color: #666666; border-radius: 5px; padding: 5px"><%= tag %></span>
                <% end %>
                <div class="good">
                <i class="fas fa-heart"></i>
                <%= prolog.likes_count %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>