config/routes.rb
Rails.application.routes.draw do
  root to: "tops#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  } 
  resources :programminglogs do
    resources :comments, only: :create
    resources :likes, only: [:index, :create, :destroy]
      collection do
        get 'search'
      end
    end
  resources :users, except: [:new]
  resources :expositions, only: [:index]
end

app/models/programminglog.rb
class Programminglog < ApplicationRecord
  validates :title, :text, presence: true 
  belongs_to :user
  has_many :comments

  has_many :likes, dependent: :destroy

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def self.search(search)
    if search
      Programminglog.where('text LIKE(?) OR title LIKE(?) ', "%#{search}%", "%#{search}%")
    else 
      Programminglog.all
    end
  end

  mount_uploader :image, ImageUploader

  acts_as_taggable
end

app/controllers/programminglogs_controller.rb
class ProgramminglogsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_programminglog, only: [:edit, :show]

  def index
    @programminglogs = Programminglog.includes(:user).order("created_at DESC")
  end
  def new
    @programminglog = Programminglog.new
  end
  def create
    # binding.pry
    Programminglog.create(programminglog_params)
    redirect_to programminglogs_path
  end
  def show
    @like = Like.new
    @comment = Comment.new
    @comments = @programminglog.comments.includes(:user)
  end
  def search
    @programminglogs = Programminglog.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end
  def edit
  end
  def update
    programminglog = Programminglog.find(params[:id])
    programminglog.update(programminglog_params)
    redirect_to programminglogs_path
  end
  def destroy
    programminglog = Programminglog.find(params[:id])
    programminglog.destroy
    redirect_to programminglogs_path
  end
  
  private
  def programminglog_params
    params.require(:programminglog).permit(:title, :image, :text, :tag_list).merge(user_id: current_user.id)
  end

  def set_programminglog
    @programminglog = Programminglog.find(params[:id])
  end


end

app/helpers/programminglogs_helper.rb
module ProgramminglogsHelper
end

app/views/programminglogs/_prolog.html.erb
<div class="textonly">
  <%= link_to(programminglog_path(prolog.id), class: 'list-content') do %>
  <div class="text__left">
    <div class="text__image" style="background-image: url(<%= prolog.image %>);"></div>
  </div>
  <div class="text__right">
    <div class="text__title">
      <%= link_to prolog.title, programminglog_path(prolog.id), class: "content__right__top--title" %>
    </div>
    <div class="text__bottom">
      <div class="text__time">
        <%= prolog.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
      </div>
      <div class="user__name">
        <img src=<%= prolog.user.image %> class = "icon_image">
        <div class="content__right__bottom--username">
          <%= link_to prolog.user.name, user_path(prolog.user), class: "content__right__bottom--userName--btn" %>
        </div>
      </div>
      <% prolog.tag_list.each do |tag| %>
        <span style="background-color: #EEEEEE; color: #666666; border-radius: 5px; padding: 5px"><%= tag %></span>
      <% end %>
      <div class="good">
      <i class="fas fa-heart"></i>
      <%= prolog.likes_count %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/programminglogs/edit.html.erb
<div class="index-page_edit">
  <%= link_to programminglogs_path do %>
    <i class="fas fa-arrow-circle-left"></i>
  <% end %>
  <div class="content__title">
    投稿の編集
  </div>

  <%= form_with model: @programminglog, class: :form, local: true do |f|%>
    <%= f.text_field :title, placeholder: :タイトル, class: :form__title %>
    <%= f.file_field :image, placeholder: :画像, class: :form__image, id: "file" %>
    <%= f.text_area :text, placeholder: :本文, class: :form__text %>
    <%= f.submit '編集する', class: :submit__btn %>
  <% end %>
</div>

app/views/programminglogs/index.html.erb
<header>
  <nav class="main_nav">
    <div class="nav">
      <ul class="nav-nav">

        <li class="nav-item choice">
          <%= link_to new_programminglog_path, class: "nav_new" do %>
            <i class="far fa-file"></i> 新規投稿
          <% end %>
        </li>

        <li class="nav_user choice">
          <%= link_to users_path, class: "nav-all" do %>
            <i class="fas fa-users"></i> ユーザー一覧
          <% end %>
        </li>

        <li class="nav_good choice">
          <%= link_to programminglog_likes_path(@programminglogs), class: "nav-user" do %>
            <i class="fas fa-heart"></i> いいね！ランキング
          <% end %>
        </li>

        <li class="user_nav choice">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>ログアウト
          <% end %>
        <% end %>

        <li class="user choice">
          <%= link_to expositions_path do %>
          <i class="fas fa-exclamation-circle"></i> 初めて使う方へ
        <% end %>

      </ul>
    
      <div class="search">
        <div class="search-box">
          <%= form_with(url: search_programminglogs_path, local: true, method: :get, class: "search-form") do |form| %>
            <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
            <%= form.submit "検索", class: "search-btn" %>
          <% end %>
        </div>
      </div>

    </div>
  </nav>
</header>

<div class="index-page">
  <div class="index-page__main">

    <div class="prolog-toppage">
      <p>Prolog</p>
    </div>

    <div class="texts">
      <div class="text">
        <% @programminglogs.each do |prolog|%>
          <%= render partial: "prolog", locals: { prolog: prolog } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<footer>
  <p>
    &Copy Prolog 2020.
  </p>
</footer>

app/views/programminglogs/new.html.erb
<div class="new-page">
  <div class="back-icon">
    <%= link_to programminglogs_path do %>
    <i class="fas fa-arrow-left"></i>
    <% end %>
  </div> 
  <div class="new-page-title">
    <h1>new post</h1>
  </div>

  <%= form_with model: @programminglog, class: :form, local: true do |f|%>
    <%= f.text_field :title, placeholder: :タイトル, class: :form__title %>
    <%= f.file_field :image, placeholder: :画像, class: :form__image, id: "file" %>
    <%= f.label :tag_list, '' %>
    <%= text_field_tag 'programminglog[tag_list]', @programminglog.tag_list, class: "form-control" %>
    <%= f.text_area :text, placeholder: :本文, class: :form__text %>
    <%= f.submit '投稿する', class: :submit__btn %>
  <% end %>
</div>

app/views/programminglogs/search.html.erb
<div class="search_index">
  <div class="back-icon">
    <%= link_to programminglogs_path do %>
    <i class="fas fa-arrow-left"></i>
    <% end %>
  </div> 
  <div class="index-page_search">
    <div class="index-page__main">
      <div class="prolog-toppage">
        <p>Prolog</p>
      </div>

      <div class="texts">
        <div class="text">
          <% @programminglogs.each do |prolog|%>
            <%= render partial: "prolog", locals: { prolog: prolog } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/programminglogs/show.html.erb
<div class="index-page_show">
  <div class="back-icon">
    <%= link_to programminglogs_path do %>
    <i class="fas fa-arrow-left"></i>
    <% end %>
  </div> 

  <div class="showpage">
    <div class="prologimage">
      <%=  link_to @programminglog.image.url, 'data-lightbox': @programminglog.image do %>
        <%= image_tag @programminglog.image.url %>
      <% end %>
    </div> 

    <div class="prolog-overrall">
      <div class="prolog-all">
        <div class="prologtitle">
          <%= @programminglog.title %>
        </div>  
        <% @programminglog.tag_list.each do |tag| %>
          <span style="background-color: #EEEEEE; color: #666666; border-radius: 5px; padding: 5px"><%= tag %></span>
        <% end %>
        <div class="prologdate">
          <%= @programminglog.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
        </div>
        <% if user_signed_in? && current_user.id == @programminglog.user_id %>
          <div class="prolog">
            <%= link_to "編集", edit_programminglog_path(@programminglog.id), class: "prolog__edit" %>
            <%= link_to "削除", programminglog_path(@programminglog.id), method: :delete, class: "prolog__delete" %>
          </div>
        <% end %>
          <div class="prologtext">
            <%= simple_format text_url_to_link(h(@programminglog.text)).html_safe %>
          </div>
          <div id="likes_buttons_<%= @programminglog.id %>">
            <%= render partial: 'likes/like', locals: { programminglog: @programminglog, likes: @likes} %>
          </div>
          <div class="container">
            <% if current_user %>
              <%= form_with(model: [@programminglog, @comment], local: true) do |f| %>
                <%= f.text_area :text, placeholder: "コメントを入力してください。", class: "comments" %>
                <div class="c_btn">
                <%= f.submit "コメント", class: "comment_btn" %>
                </div>
              <% end %>
            <% else %>
              <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
            <% end %>
          </div>
          <div class="comments">
            <h5>＜コメント一覧＞</h5>
            <% if @comments %>
              <% @comments.each do |comment| %>
                <p>
                  <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %>：</strong>
                  <%= comment.text%>
                </p>
              <% end %>
            <% end %>
          </div>
    </div>
  </div>
</div>